name: Deploy
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Print Version
        run: node -v

      - name: Install Dependencies
        run: npm ci

      - name: Run Test
        run: npm run test